[build]
command = "react-router build && node scripts/patch-node-fetch-server.js"
publish = "build/client"

[dev]
command = "react-router dev"

[functions]
external_node_modules = ["@mjackson/node-fetch-server"]
